input.onButtonEvent(Button.A, input.buttonEventClick(), function () {
    pins.digitalWritePin(DigitalPin.C4, 0)
    pins.digitalWritePin(DigitalPin.C5, 1)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.C9, 1)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.C8, 0)
    pins.digitalWritePin(DigitalPin.C9, 0)
    pins.digitalWritePin(DigitalPin.C10, 1)
})
pins.digitalWritePin(DigitalPin.C4, 1)
pins.digitalWritePin(DigitalPin.C5, 0)
pins.digitalWritePin(DigitalPin.C8, 1)
pins.digitalWritePin(DigitalPin.C9, 0)
pins.digitalWritePin(DigitalPin.C10, 0)
